### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by kazigk** [thefloweringash/iousbhiddriver-descriptor-override#29]
```
iMac-kazi:iousbhiddriver-descriptor-override kazi$ xcodebuild
2016-03-28 01:14:57.714 xcodebuild[364:3826] Failed to locate a valid instance of CoreSimulatorService in the bootstrap.  Adding it now.
=== BUILD LEGACY TARGET Info-Plist OF PROJECT IOUSBHIDDriverDescriptorOverride WITH THE DEFAULT CONFIGURATION (Release) ===

Check dependencies

ExternalBuildToolExecution Info-Plist
    cd /Users/kazi/iousbhiddriver-descriptor-override
    export ACTION=
    /usr/local/bin/rake Info.plist
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby scripts/build-plist.rb
/Users/kazi/iousbhiddriver-descriptor-override/scripts/hidutil.rb:286:in `compact_usages': undefined method `slice_when' for #<Array:0x007f8a9b292b60> (NoMethodError)
	from /Users/kazi/iousbhiddriver-descriptor-override/scripts/hidutil.rb:208:in `initialize'
	from /Users/kazi/iousbhiddriver-descriptor-override/scripts/hidutil.rb:375:in `new'
	from /Users/kazi/iousbhiddriver-descriptor-override/scripts/hidutil.rb:375:in `parse'
	from scripts/build-plist.rb:12:in `fix_descriptor'
	from scripts/build-plist.rb:29:in `block (2 levels) in <main>'
	from scripts/build-plist.rb:22:in `each'
	from scripts/build-plist.rb:22:in `each_with_index'
	from scripts/build-plist.rb:22:in `block in <main>'
	from scripts/build-plist.rb:20:in `each'
	from scripts/build-plist.rb:20:in `<main>'
rake aborted!
Command failed with status (1): [/System/Library/Frameworks/Ruby.framework/...]
/Users/kazi/iousbhiddriver-descriptor-override/Rakefile:23:in `block in <top (required)>'
Tasks: TOP => Info.plist
(See full trace by running task with --trace)
Command /usr/local/bin/rake failed with exit code 1

** BUILD FAILED **


The following build commands failed:
	ExternalBuildToolExecution Info-Plist
(1 failure)
iMac-kazi:iousbhiddriver-descriptor-override kazi$ 
```

**Comment by kazigk** [comment]
I just updated Ruby and… it works! ^_^
