### ISSUE TITLE
xcodebuild failed in OSX EI Capitan

### ISSUE THREAD

**Issue by szj727** [thefloweringash/iousbhiddriver-descriptor-override#32]
=== BUILD LEGACY TARGET Info-Plist OF PROJECT IOUSBHIDDriverDescriptorOverride WITH THE DEFAULT CONFIGURATION (Release) ===

Check dependencies

ExternalBuildToolExecution Info-Plist
    cd /Users/szj/workspace/noppoo/iousbhiddriver-descriptor-override
    export ACTION=
    /usr/local/bin/rake Info.plist
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby scripts/build-plist.rb
/Users/szj/workspace/noppoo/iousbhiddriver-descriptor-override/scripts/hidutil.rb:286:in `compact_usages': undefined method `slice_when' for #<Array:0x007fef535e7eb0> (NoMethodError)
       	from /Users/szj/workspace/noppoo/iousbhiddriver-descriptor-override/scripts/hidutil.rb:208:in `initialize'
       	from /Users/szj/workspace/noppoo/iousbhiddriver-descriptor-override/scripts/hidutil.rb:375:in `new'
       	from /Users/szj/workspace/noppoo/iousbhiddriver-descriptor-override/scripts/hidutil.rb:375:in `parse'
       	from scripts/build-plist.rb:12:in `fix_descriptor'
       	from scripts/build-plist.rb:29:in `block (2 levels) in <main>'
       	from scripts/build-plist.rb:22:in `each'
       	from scripts/build-plist.rb:22:in `each_with_index'
       	from scripts/build-plist.rb:22:in `block in <main>'
       	from scripts/build-plist.rb:20:in `each'
       	from scripts/build-plist.rb:20:in `<main>'
rake aborted!
Command failed with status (1): [/System/Library/Frameworks/Ruby.framework/...]
/Users/szj/workspace/noppoo/iousbhiddriver-descriptor-override/Rakefile:23:in `block in <top (required)>'
Tasks: TOP => Info.plist
(See full trace by running task with --trace)
Command /usr/local/bin/rake failed with exit code 1

** BUILD FAILED **

The following build commands failed:
       	ExternalBuildToolExecution Info-Plist

**Comment by thefloweringash** [comment]
This looks like a ruby version issue. Try installing a newer version from homebrew (2.2+).

**Comment by szj727** [comment]
Thank you very much, This work for my mbp with OSX EI Captain:
updated to ruby 2.3.0
disabled the SIP
change to branch ft-el-cap
